### ISSUE TITLE
Segmentation fault when running with my data

### ISSUE THREAD

**Issue by fnaji** [tercen/clusteringmetrics_operator#1]
*** caught segfault ***
address 0x560718b76cd8, cause 'memory not mapped'

Traceback:
1: intCriteria(data, as.integer(labs[, 1]), c("Davies_Bouldin", "Dunn", "Silhouette", "Calinski_Harabasz"))
An irrecoverable exception occurred. R is aborting now ...

**Comment by fnaji** [comment]
Here is a[workflow ](https://tercen.com/tercenTest/w/9a97785fd634410be6576620a7b8a4bb)with the issue

**Comment by agouy** [comment]
Solved in version [0.0.2](https://github.com/tercen/clustering_metrics_operator/releases/tag/0.2.0)
